excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://StarWar.github.io
title: Raj Rathore
email: 
author: Raj
description: Stuff I like to talk about: my work, opinions and ideas.
paginate: 3
google_analytics: UA-69024344-1
